### ISSUE TITLE
Add ability to mirror the output horizontally

### ISSUE THREAD

**Issue by Poodmund** [Sigma88/Sigma-Cartographer#5]
As KSP requires a differently oriented input map as apposed to the -180 to 180 LON output that you'd expect, if a user is utilizing Cartographer to output maps that are then used for the Color Map/Normal Map, for example, they have to take the Cartographer output maps, flip them horizontally then offset them by -90deg LON so that they are correctly oriented and aligned to be used as the input textures for KSP.

The offset by 90deg LON is already achievable with Cartographer as LON & LAT offset has been implemented yet the horizontal mirroring is not available unfortunately.

Is there the possibility to mirror Cartographer's map output so that when combined with a LON offset, the output can be used directly as KSP textures?

EDIT: For reference, HeightmapExtractor did something similar as can be seen here: https://github.com/StupidChris/HeightmapExtractor/blob/320677a6bb1686157ec2e0e7beb64cc3b1ced304/HeightmapExtractor/MapExtractor.cs#L119

**Comment by Sigma88** [comment]
I can add this, but it will only mirror the single tiles, it won't change the numbering scheme

is that enough?



(tile 0 will be on the right instead of the left)

**Comment by Sigma88** [comment]
I've added flipV and flipH to flip vertically and horizontally

they both are "false" by default

I haven't compiled the code yet, I'll send you a dll as soon as I have my laptop, or you can compile it yourself if you know how to do that

**Comment by Sigma88** [comment]
> If you use flipH = true and export a map, does what used to be Tile 1 become Tile 0 and is mirrored horizontally, if so, that would be the desired output.

no, Tile 1 will remain Tile 1, but it will be mirrored horizontally

**Comment by Poodmund** [comment]
The test .zip you sent me works fine and is what this issue requested to fulfill. 😄

**Comment by Sigma88** [comment]
released
